import type { ModelInfo } from "../model.js"

export interface FreeRouterModelEntry {
	id: string
	name: string
	provider: "openrouter" | "gemini" | "custom"
	contextWindow: number
	maxTokens: number
	enabled: boolean
	description?: string
}

export const freeRouterDefaultModelId = "google/gemma-4-31b-it:free"

export const freeRouterDefaultModelInfo: ModelInfo = {
	maxTokens: 32_768,
	contextWindow: 262_144,
	supportsImages: true,
	supportsPromptCache: true,
	inputPrice: 0.0,
	outputPrice: 0.0,
	cacheWritesPrice: 0.0,
	cacheReadsPrice: 0.0,
	description: "Google Gemma 4 31B (Free Tier) — Multimodal open model routed via OpenRouter free tier.",
}

export const freeRouterModels: Record<string, ModelInfo> = {
	"google/gemma-4-31b-it:free": {
		maxTokens: 32_768,
		contextWindow: 262_144,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description:
			"Google Gemma 4 31B (Free) — Dense multimodal model with 262k context, vision support, and strong coding capabilities.",
	},
	"qwen/qwen3.8-27b:free": {
		maxTokens: 32_768,
		contextWindow: 262_144,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description:
			"Qwen 3.8 27B (Free) — Frontier open-weight model with strong code synthesis, refactoring, and agentic workflows.",
	},
	"cohere/north-mini-code:free": {
		maxTokens: 32_768,
		contextWindow: 256_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description: "Cohere North Mini Code (Free) — Purpose-built code reasoning and generation model.",
	},
	"nvidia/nemotron-3-ultra-550b-a55b:free": {
		maxTokens: 32_768,
		contextWindow: 1_000_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description:
			"NVIDIA Nemotron 3 Ultra 550B MoE (Free) — Massive 1M context window for large codebase comprehension.",
	},
	"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free": {
		maxTokens: 32_768,
		contextWindow: 256_000,
		supportsImages: true,
		supportsPromptCache: true,
		preserveReasoning: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description:
			"NVIDIA Nemotron 3 Nano Omni (Free) — High reasoning chain-of-thought model with 256k context and multimodal support.",
	},
	"z-ai/glm-5.2:free": {
		maxTokens: 16_384,
		contextWindow: 32_768,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description: "Z.ai GLM 5.2 (Free) — Fast, efficient model for quick queries and edits.",
	},
	"nex-agi/nex-n2.5-pro:free": {
		maxTokens: 32_768,
		contextWindow: 262_144,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description: "Nex AGI Nex-N2.5-Pro (Free) — 262k context multimodal reasoning model.",
	},
	"thinkingmachines/inkling:free": {
		maxTokens: 32_768,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description: "Thinking Machines Inkling (Free) — 1M token context reasoning model.",
	},
	"meta-llama/llama-3.3-70b-instruct:free": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description:
			"Meta Llama 3.3 70B Instruct (Free) — Frontier open-weight model with strong coding and instruction following.",
	},
	"deepseek/deepseek-r1:free": {
		maxTokens: 8192,
		contextWindow: 128_000,
		supportsImages: false,
		supportsPromptCache: true,
		preserveReasoning: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description: "DeepSeek R1 (Free) — Open-weights reasoning model with full chain-of-thought capabilities.",
	},
	"google/gemini-2.0-flash-exp:free": {
		maxTokens: 8192,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description:
			"Google Gemini 2.0 Flash Experimental (Free) — High speed with 1M context window and vision support.",
	},
	"qwen/qwen-2.5-coder-32b-instruct:free": {
		maxTokens: 8192,
		contextWindow: 32_768,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description: "Qwen 2.5 Coder 32B Instruct (Free) — Specialized code generation and debugging model.",
	},
	"mistralai/mistral-small-24b-instruct-2501:free": {
		maxTokens: 8192,
		contextWindow: 32_768,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description: "Mistral Small 24B (Free) — Fast, efficient instruction-tuned model with strong reasoning.",
	},
	"deepseek/deepseek-chat:free": {
		maxTokens: 8192,
		contextWindow: 64_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.0,
		outputPrice: 0.0,
		cacheWritesPrice: 0.0,
		cacheReadsPrice: 0.0,
		description: "DeepSeek V3 (Free) — Low latency versatile model for rapid chat and iterative edits.",
	},
}

export const DEFAULT_FREE_ROUTER_MODELS: FreeRouterModelEntry[] = [
	{
		id: "google/gemma-4-31b-it:free",
		name: "Google Gemma 4 31B (OpenRouter Free)",
		provider: "openrouter",
		contextWindow: 262_144,
		maxTokens: 32_768,
		enabled: true,
		description: "Google DeepMind's 31B dense multimodal model with 262k context and strong coding capabilities",
	},
	{
		id: "qwen/qwen3.8-27b:free",
		name: "Qwen 3.8 27B (OpenRouter Free)",
		provider: "openrouter",
		contextWindow: 262_144,
		maxTokens: 32_768,
		enabled: true,
		description: "Top-tier open weights model for complex coding, refactoring, and agentic workflows",
	},
	{
		id: "cohere/north-mini-code:free",
		name: "Cohere North Mini Code (OpenRouter Free)",
		provider: "openrouter",
		contextWindow: 256_000,
		maxTokens: 32_768,
		enabled: true,
		description: "Specialized code generation, refactoring, and debugging model by Cohere",
	},
	{
		id: "nvidia/nemotron-3-ultra-550b-a55b:free",
		name: "NVIDIA Nemotron 3 Ultra (OpenRouter Free)",
		provider: "openrouter",
		contextWindow: 1_000_000,
		maxTokens: 32_768,
		enabled: true,
		description: "Frontier 550B MoE open model with 1M context window for large codebase comprehension",
	},
	{
		id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
		name: "NVIDIA Nemotron 3 Nano Omni (OpenRouter Free)",
		provider: "openrouter",
		contextWindow: 256_000,
		maxTokens: 32_768,
		enabled: true,
		description: "High-reasoning chain-of-thought model with 256k context for complex debugging",
	},
	{
		id: "z-ai/glm-5.2:free",
		name: "Z.ai GLM 5.2 (OpenRouter Free)",
		provider: "openrouter",
		contextWindow: 32_768,
		maxTokens: 16_384,
		enabled: true,
		description: "Fast conversational agent for quick questions and lightweight edits",
	},
	{
		id: "nex-agi/nex-n2.5-pro:free",
		name: "Nex AGI Nex-N2.5-Pro (OpenRouter Free)",
		provider: "openrouter",
		contextWindow: 262_144,
		maxTokens: 32_768,
		enabled: true,
		description: "Versatile reasoning model with 262k context and multimodal support",
	},
	{
		id: "thinkingmachines/inkling:free",
		name: "Thinking Machines Inkling (OpenRouter Free)",
		provider: "openrouter",
		contextWindow: 1_048_576,
		maxTokens: 32_768,
		enabled: true,
		description: "1M token context reasoning model for whole-codebase comprehension",
	},
]
