
const fs = require('fs');

function buildCompleter() {
  let code = [];
  
  code.push("import { LLMProvider, ChatMessage } from '../types';");
  code.push("import { streamOllamaChat, streamDeepSeekChat } from '../services/api-service';");
  code.push("import { RateLimiter } from '../services/rate-limiter';");
  code.push("import { TelemetryService } from '../services/telemetry-service';");
  code.push("import { AgentParser } from './agent-parser';");
  code.push("");
  code.push("/** Handles LLM streaming completion calls and context summarization */");
  code.push("export class AgentCompleter {");
  code.push("  private readonly _rateLimiter = RateLimiter.getInstance();");
  code.push("  private readonly _telemetry = TelemetryService.getInstance();");
  code.push("  private readonly _parser = new AgentParser();");
  code.push("  private _lastLatencyMeasurement = 0;");
  code.push("");
  code.push("  constructor(");
  code.push("    private readonly _postMessage: (msg: any) => void,");
  code.push("    private readonly _getSecret: (key: string) => Promise<string | undefined>,");
  code.push("  ) {}");
  code.push("");
  code.push("  public get lastLatency(): number {");
  code.push("    return this._lastLatencyMeasurement;");
  code.push("  }");
  code.push("");
  code.push("  /**");
  code.push("   * Get a completion from the LLM via streaming.");
  code.push("   * Returns the full assistant response text.");
  code.push("   */");
  code.push("  public async getLLMCompletion(");
  code.push("    provider: LLMProvider,");
  code.push("    host: string,");
  code.push("    model: string,");
  code.push("    apiKey: string,");
  code.push("    messages: { role: 'user' | 'assistant' | 'system'; content: string; images?: string[] }[],");
  code.push("    signal: AbortSignal,");
  code.push("    currentSessionId: string,");
  code.push("    completionController?: AbortController,");
  code.push("  ): Promise<string> {");
  code.push("    const startTime = Date.now();");
  code.push("    return new Promise((resolve, reject) => {");
  code.push("      let fullText = '';");
  code.push("      let isFinished = false;");
  code.push("      let capturedUsage: { promptTokens: number; completionTokens: number } | undefined;");
  code.push("");
  code.push("      const onComplete = (completedText: string, usage?: { promptTokens: number; completionTokens: number }) => {");
  code.push("        if (isFinished) return;");
  code.push("        isFinished = true;");
  code.push("        const cleaned = this._parser.getCleanedToolResponse(completedText);");
  code.push("        this._postMessage({ type: 'chatResponseComplete', fullText: cleaned });");
  code.push("");
  code.push("        if (usage) {");
  code.push("          capturedUsage = usage;");
  code.push("          const inputTokens = usage.promptTokens;");
  code.push("          const outputTokens = usage.completionTokens;");
  code.push("          const isDeepSeek = provider === 'deepseek';");
  code.push("          const inputCost = isDeepSeek ? (inputTokens / 1000000) * 0.14 : 0;");
  code.push("          const outputCost = isDeepSeek ? (outputTokens / 1000000) * 0.28 : 0;");
  code.push("          const totalCost = inputCost + outputCost;");
  code.push("");
  code.push("          this._postMessage({");
  code.push("            type: 'tokenUsage',");
  code.push("            usage: {");
  code.push("              input: inputTokens,");
  code.push("              output: outputTokens,");
  code.push("              total: inputTokens + outputTokens,");
  code.push("              cost: totalCost,");
  code.push("            },");
  code.push("          });");
  code.push("");
  code.push("          this._rateLimiter.recordUsage(currentSessionId, inputTokens, outputTokens);");
  code.push("");
  code.push("          const latency = Date.now() - startTime;");
  code.push("          this._lastLatencyMeasurement = latency;");
  code.push("          this._telemetry.recordCall({");
  code.push("            sessionId: currentSessionId,");
  code.push("            sessionTitle: 'Active Session',");
  code.push("            tokensInput: inputTokens,");
  code.push("            tokensOutput: outputTokens,");
  code.push("            cost: totalCost,");
  code.push("            latency,");
  code.push("            provider,");
  code.push("            model,");
  code.push("            error: false,");
  code.push("            toolCalls: this._parser.parseToolCalls(completedText).length,");
  code.push("          });");
  code.push("        }");
  code.push("");
  code.push("        resolve(cleaned);");
  code.push("      };");
  code.push("");
  code.push("      const onError = (err: any) => {");
  code.push("        if (isFinished) return;");
  code.push("        isFinished = true;");
  code.push("");
  code.push("        const latency = Date.now() - startTime;");
  code.push("        const inputTokens = RateLimiter.estimateTokens(JSON.stringify(messages));");
  code.push("        const outputTokens = RateLimiter.estimateTokens(fullText);");
  code.push("        this._telemetry.recordCall({");
  code.push("          sessionId: currentSessionId,");
  code.push("          sessionTitle: 'Active Session',");
  code.push("          tokensInput: inputTokens,");
  code.push("          tokensOutput: outputTokens,");
  code.push("          cost: 0,");
  code.push("          latency,");
  code.push("          provider,");
  code.push("          model,");
  code.push("          error: true,");
  code.push("          errorMessage: err.message || 'Unknown error',");
  code.push("        });");
  code.push("");
  code.push("        this._rateLimiter.recordFailure();");
  code.push("        reject(err);");
  code.push("      };");
  code.push("");
  code.push("      if (provider === 'ollama') {");
  code.push("        streamOllamaChat(");
  code.push("          host,");
  code.push("          model,");
  code.push("          messages,");
  code.push("          signal,");
  code.push("          (chunk) => {");
  code.push("            if (isFinished) return;");
  code.push("            fullText += chunk;");
  code.push("            this._postMessage({ type: 'chatResponseChunk', text: chunk });");
  code.push("");
  code.push("            if (this._parser.hasCompleteToolCall(fullText)) {");
  code.push("              completionController?.abort();");
  code.push("              onComplete(fullText, capturedUsage);");
  code.push("            }");
  code.push("          },");
  code.push("          (completedText, usage) => {");
  code.push("            if (usage) capturedUsage = usage;");
  code.push("            onComplete(completedText, usage);");
  code.push("          },");
  code.push("          onError,");
  code.push("        );");
  code.push("      } else {");
  code.push("        streamDeepSeekChat(");
  code.push("          apiKey,");
  code.push("          model,");
  code.push("          messages,");
  code.push("          signal,");
  code.push("          (chunk) => {");
  code.push("            if (isFinished) return;");
  code.push("            fullText += chunk;");
  code.push("            this._postMessage({ type: 'chatResponseChunk', text: chunk });");
  code.push("");
  code.push("            if (this._parser.hasCompleteToolCall(fullText)) {");
  code.push("              completionController?.abort();");
  code.push("              onComplete(fullText, capturedUsage);");
  code.push("            }");
  code.push("          },");
  code.push("          (completedText, usage) => {");
  code.push("            if (usage) capturedUsage = usage;");
  code.push("            onComplete(completedText, usage);");
  code.push("          },");
  code.push("          onError,");
  code.push("        );");
  code.push("      }");
  code.push("    });");
  code.push("  }");
  code.push("");
  code.push("  /**");
  code.push("   * Summarize conversation history for context compression.");
  code.push("   */");
  code.push("  public async summarizeHistory(");
  code.push("    provider: LLMProvider,");
  code.push("    host: string,");
  code.push("    model: string,");
  code.push("    apiKey: string,");
  code.push("    historyToSummarize: ChatMessage[],");
  code.push("  ): Promise<string> {");
  code.push("    const summarizePrompt = 'You are a helpful pair programming assistant. Please summarize the following conversation history between a developer and an AI assistant. Provide a highly dense, bulleted summary of key decisions, context details, executed actions, and technical changes. Do not lose key file names, error messages, or environment information:\\n';");
  code.push("    + historyToSummarize.map((msg) => msg.role.toUpperCase() + ': ' + msg.content).join('\\n\\n');");
  code.push("");
  code.push("    const messages = [{ role: 'user' as const, content: summarizePrompt }];");
  code.push("");
  code.push("    return new Promise<string>((resolve, reject) => {");
  code.push("      const controller = new AbortController();");
  code.push("      if (provider === 'ollama') {");
  code.push("        streamOllamaChat(");
  code.push("          host,");
  code.push("          model,");
  code.push("          messages,");
  code.push("          controller.signal,");
  code.push("          () => {},");
  code.push("          (fullText) => resolve(fullText),");
  code.push("          (err) => reject(err),");
  code.push("        );");
  code.push("      } else {");
  code.push("        streamDeepSeekChat(");
  code.push("          apiKey,");
  code.push("          model,");
  code.push("          messages,");
  code.push("          controller.signal,");
  code.push("          () => {},");
  code.push("          (fullText) => resolve(fullText),");
  code.push("          (err) => reject(err),");
  code.push("        );");
  code.push("      }");
  code.push("    });");
  code.push("  }");
  code.push("");
  code.push("  /** Parse tool calls from text */");
  code.push("  public parseToolCalls(text: string) {");
  code.push("    return this._parser.parseToolCalls(text);");
  code.push("  }");
  code.push("");
  code.push("  /** Get cleaned tool response */");
  code.push("  public getCleanedToolResponse(text: string) {");
  code.push("    return this._parser.getCleanedToolResponse(text);");
  code.push("  }");
  code.push("");
  code.push("  /** Check if text has complete tool call */");
  code.push("  public hasCompleteToolCall(text: string) {");
  code.push("    return this._parser.hasCompleteToolCall(text);");
  code.push("  }");
  code.push("}");
  code.push("");
  
  return code.join('\n');
}

const result = buildCompleter();
fs.writeFileSync('src/agent/agent-completer.ts', result, 'utf8');
console.log('Done - wrote ' + result.length + ' bytes');
