
const fs = require('fs');

// Build agent-parser.ts
// Note: We avoid literal '<toolName' patterns to prevent XML tag parsing issues
// All tool names and regex are constructed safely

function buildParser() {
  let code = [];
  
  code.push("import { ToolCall } from './types';");
  code.push("");
  code.push("/**");
  code.push(" * Parses tool calls from raw LLM response text.");
  code.push(" * Handles: stripping code blocks, auto-closing tags, cleaning responses,");
  code.push(" * and enforcing one-tool-per-turn.");
  code.push(" */");
  code.push("export class AgentParser {");
  code.push("  /**");
  code.push("   * Remove fenced code blocks from text before tool-tag scanning.");
  code.push("   */");
  code.push("  public stripCodeBlocks(text: string): string {");
  code.push("    let result = text.replace(/\\x60\\x60\\x60[\\s\\S]*?\\x60\\x60\\x60/g, '');");
  code.push("    result = result.replace(/`[^`\\n]*?`/g, '');");
  code.push("    result = result.replace(/&lt;\\/?[a-z_]+[\\s\\S]*?\\/?&gt;/gi, '');");
  code.push("    return result;");
  code.push("  }");
  code.push("");
  code.push("  private isTagFullyClosed(text: string, toolName: string): boolean {");
  code.push("    const openTag = '\\u003C' + toolName;");
  code.push("    const startIdx = text.toLowerCase().indexOf(openTag);");
  code.push("    if (startIdx === -1) return false;");
  code.push("    let inDq = false;");
  code.push("    let inSq = false;");
  code.push("    let escaped = false;");
  code.push("    for (let i = startIdx + openTag.length; i < text.length; i++) {");
  code.push("      const char = text[i];");
  code.push("      if (escaped) { escaped = false; continue; }");
  code.push("      if (char === '\\\\') { escaped = true; continue; }");
  code.push("      if (char === '\"' && !inSq) { inDq = !inDq; continue; }");
  code.push("      if (char === \"'\" && !inDq) { inSq = !inSq; continue; }");
  code.push("      if (char === '\\u003E' && !inDq && !inSq) { return true; }");
  code.push("    }");
  code.push("    return false;");
  code.push("  }");
  code.push("");
  code.push("  public hasCompleteToolCall(text: string): boolean {");
  code.push("    const stripped = this.stripCodeBlocks(text);");
  code.push("    const selfClosingTools = [");
  code.push("      'read_file', 'list_dir', 'grep_search', 'web_search',");
  code.push("      'browser_navigate', 'browser_click', 'browser_type',");
  code.push("      'browser_evaluate_script', 'browser_screenshot',");
  code.push("      'figma_inspect', 'run_command', 'close_terminal',");
  code.push("      'read_terminal', 'list_terminals',");
  code.push("    ];");
  code.push("    for (const tool of selfClosingTools) {");
  code.push("      if (this.isTagFullyClosed(stripped, tool)) return true;");
  code.push("    }");
  code.push("    const blockTools = ['create_file', 'write_file', 'patch_file', 'send_terminal_input'];");
  code.push("    for (const tool of blockTools) {");
  code.push("      const closeTag = '\\u003C\\u002F' + tool + '\\\\s*\\u003E';");
  code.push("      const regex = new RegExp(closeTag, 'i');");
  code.push("      if (regex.test(stripped)) return true;");
  code.push("    }");
  code.push("    return false;");
  code.push("  }");
  code.push("");
  code.push("  private autoCloseToolTags(text: string): string {");
  code.push("    const blockTools = ['create_file', 'write_file', 'patch_file', 'send_terminal_input'];");
  code.push("    let adjustedText = text;");
  code.push("    for (const tool of blockTools) {");
  code.push("      const openTag = '\\u003C' + tool + '(\\\\s+[^>]*?)?\\u003E';");
  code.push("      const openRegex = new RegExp(openTag, 'i');");
  code.push("      const closeTag = '\\u003C\\u002F' + tool + '\\\\s*\\u003E';");
  code.push("      const closeRegex = new RegExp(closeTag, 'i');");
  code.push("      if (openRegex.test(adjustedText) && !closeRegex.test(adjustedText)) {");
  code.push("        adjustedText = adjustedText.trimEnd() + '\\\\n\\u003C\\u002F' + tool + '\\u003E';");
  code.push("      }");
  code.push("    }");
  code.push("    return adjustedText;");
  code.push("  }");
  code.push("");
  code.push("  public getCleanedToolResponse(text: string): string {");
  code.push("    const closedText = this.autoCloseToolTags(text);");
  code.push("    const stripped = this.stripCodeBlocks(closedText);");
  code.push("    const selfClosingTools = [");
  code.push("      'read_file', 'list_dir', 'grep_search', 'web_search',");
  code.push("      'browser_navigate', 'browser_click', 'browser_type',");
  code.push("      'browser_evaluate_script', 'browser_screenshot',");
  code.push("      'figma_inspect', 'run_command', 'close_terminal',");
  code.push("      'read_terminal', 'list_terminals',");
  code.push("    ];");
  code.push("    let earliestEnd = -1;");
  code.push("    for (const tool of selfClosingTools) {");
  code.push("      const openTag = '\\u003C' + tool + '[^>]*\\u003E';");
  code.push("      const regex = new RegExp(openTag, 'i');");
  code.push("      const m = regex.exec(stripped);");
  code.push("      if (m) {");
  code.push("        const escaped = m[0].replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');");
  code.push("        const origM = new RegExp(escaped).exec(closedText);");
  code.push("        if (origM) {");
  code.push("          const endIdx = origM.index + origM[0].length;");
  code.push("          if (earliestEnd === -1 || endIdx < earliestEnd) earliestEnd = endIdx;");
  code.push("        }");
  code.push("      }");
  code.push("    }");
  code.push("    const blockTools = ['create_file', 'write_file', 'patch_file', 'send_terminal_input'];");
  code.push("    for (const tool of blockTools) {");
  code.push("      const closeTag = '\\u003C\\u002F' + tool + '\\\\s*\\u003E';");
  code.push("      const regex = new RegExp(closeTag, 'i');");
  code.push("      const m = regex.exec(stripped);");
  code.push("      if (m) {");
  code.push("        const escaped = m[0].replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');");
  code.push("        const origM = new RegExp(escaped).exec(closedText);");
  code.push("        if (origM) {");
  code.push("          const endIdx = origM.index + origM[0].length;");
  code.push("          if (earliestEnd === -1 || endIdx < earliestEnd) earliestEnd = endIdx;");
  code.push("        }");
  code.push("      }");
  code.push("    }");
  code.push("    if (earliestEnd !== -1) return closedText.substring(0, earliestEnd);");
  code.push("    return closedText;");
  code.push("  }");
  code.push("");
  code.push("  private attr(attrs: string, name: string): string | null {");
  code.push("    const dqName = name + '\\\\s*=\\\\s*\"([^\"\\\\\\\\]*(?:\\\\\\\\.[^\"\\\\\\\\]*)*)\"';");
  code.push("    const dq = new RegExp(dqName, 'i').exec(attrs);");
  code.push("    if (dq) return dq[1].replace(/\\\\\"/g, '\"').replace(/\\\\\\\\/g, '\\\\');");
  code.push("    const sqName = name + \"\\\\s*=\\\\s*'([^'\\\\\\\\]*(?:\\\\\\\\.[^'\\\\\\\\]*)*)'\";");
  code.push("    const sq = new RegExp(sqName, 'i').exec(attrs);");
  code.push("    if (sq) return sq[1].replace(/\\\\'/g, \"'\").replace(/\\\\\\\\/g, '\\\\');");
  code.push("    return null;");
  code.push("  }");
  code.push("");
  code.push("  public parseToolCalls(rawText: string): ToolCall[] {");
  code.push("    const text = this.stripCodeBlocks(rawText);");
  code.push("    const candidates: { index: number; tool: ToolCall }[] = [];");
  code.push("    let match;");
  code.push("");
  code.push("    // read_file");
  code.push("    const readFileTag = '\\\\u003Cread_file([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const readFileRegex = new RegExp(readFileTag, 'gi');");
  code.push("    while ((match = readFileRegex.exec(text)) !== null) {");
  code.push("      const p = this.attr(match[1], 'path');");
  code.push("      if (p) {");
  code.push("        const sl = this.attr(match[1], 'start_line');");
  code.push("        const el = this.attr(match[1], 'end_line');");
  code.push("        const tool: ToolCall = { name: 'read_file', path: p.trim() };");
  code.push("        if (sl) tool.start_line = parseInt(sl, 10);");
  code.push("        if (el) tool.end_line = parseInt(el, 10);");
  code.push("        candidates.push({ index: match.index, tool });");
  code.push("      }");
  code.push("    }");
  code.push("");
  code.push("    // figma_inspect");
  code.push("    const figmaTag = '\\\\u003Cfigma_inspect([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const figmaInspectRegex = new RegExp(figmaTag, 'gi');");
  code.push("    while ((match = figmaInspectRegex.exec(text)) !== null) {");
  code.push("      const u = this.attr(match[1], 'url');");
  code.push("      if (u) candidates.push({ index: match.index, tool: { name: 'figma_inspect', url: u } });");
  code.push("    }");
  code.push("");
  code.push("    // list_dir");
  code.push("    const listDirTag = '\\\\u003Clist_dir([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const listDirRegex = new RegExp(listDirTag, 'gi');");
  code.push("    while ((match = listDirRegex.exec(text)) !== null) {");
  code.push("      const p = this.attr(match[1], 'path');");
  code.push("      if (p) candidates.push({ index: match.index, tool: { name: 'list_dir', path: p.trim() } });");
  code.push("    }");
  code.push("");
  code.push("    // grep_search");
  code.push("    const grepTag = '\\\\u003Cgrep_search([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const grepSearchRegex = new RegExp(grepTag, 'gi');");
  code.push("    while ((match = grepSearchRegex.exec(text)) !== null) {");
  code.push("      const q = this.attr(match[1], 'query');");
  code.push("      if (q) candidates.push({ index: match.index, tool: { name: 'grep_search', query: q } });");
  code.push("    }");
  code.push("");
  code.push("    // web_search");
  code.push("    const webTag = '\\\\u003Cweb_search([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const webSearchRegex = new RegExp(webTag, 'gi');");
  code.push("    while ((match = webSearchRegex.exec(text)) !== null) {");
  code.push("      const q = this.attr(match[1], 'query');");
  code.push("      if (q) candidates.push({ index: match.index, tool: { name: 'web_search', query: q } });");
  code.push("    }");
  code.push("");
  code.push("    // write_file");
  code.push("    const writeFileTag = '\\\\u003Cwrite_file([\\\\s\\\\S]*?)\\\\u003E([\\\\s\\\\S]*?)\\\\u003C\\\\u002Fwrite_file\\\\s*\\\\u003E';");
  code.push("    const writeFileRegex = new RegExp(writeFileTag, 'gi');");
  code.push("    while ((match = writeFileRegex.exec(text)) !== null) {");
  code.push("      const p = this.attr(match[1], 'path');");
  code.push("      if (p) candidates.push({ index: match.index, tool: { name: 'write_file', path: p.trim(), content: match[2] } });");
  code.push("    }");
  code.push("");
  code.push("    // create_file");
  code.push("    const createFileTag = '\\\\u003Ccreate_file([\\\\s\\\\S]*?)\\\\u003E([\\\\s\\\\S]*?)\\\\u003C\\\\u002Fcreate_file\\\\s*\\\\u003E';");
  code.push("    const createFileRegex = new RegExp(createFileTag, 'gi');");
  code.push("    while ((match = createFileRegex.exec(text)) !== null) {");
  code.push("      const p = this.attr(match[1], 'path');");
  code.push("      if (p) candidates.push({ index: match.index, tool: { name: 'create_file', path: p.trim(), content: match[2] } });");
  code.push("    }");
  code.push("");
  code.push("    // patch_file");
  code.push("    const patchFileTag = '\\\\u003Cpatch_file([\\\\s\\\\S]*?)\\\\u003E([\\\\s\\\\S]*?)\\\\u003C\\\\u002Fpatch_file\\\\s*\\\\u003E';");
  code.push("    const patchFileRegex = new RegExp(patchFileTag, 'gi');");
  code.push("    while ((match = patchFileRegex.exec(text)) !== null) {");
  code.push("      const p = this.attr(match[1], 'path');");
  code.push("      if (p) candidates.push({ index: match.index, tool: { name: 'patch_file', path: p.trim(), content: match[2] } });");
  code.push("    }");
  code.push("");
  code.push("    // browser_navigate");
  code.push("    const browserNavTag = '\\\\u003Cbrowser_navigate([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const browserNavRegex = new RegExp(browserNavTag, 'gi');");
  code.push("    while ((match = browserNavRegex.exec(text)) !== null) {");
  code.push("      const u = this.attr(match[1], 'url');");
  code.push("      if (u) candidates.push({ index: match.index, tool: { name: 'browser_navigate', url: u } });");
  code.push("    }");
  code.push("");
  code.push("    // browser_click");
  code.push("    const browserClickTag = '\\\\u003Cbrowser_click([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const browserClickRegex = new RegExp(browserClickTag, 'gi');");
  code.push("    while ((match = browserClickRegex.exec(text)) !== null) {");
  code.push("      const s = this.attr(match[1], 'selector');");
  code.push("      if (s) candidates.push({ index: match.index, tool: { name: 'browser_click', selector: s } });");
  code.push("    }");
  code.push("");
  code.push("    // browser_type");
  code.push("    const browserTypeTag = '\\\\u003Cbrowser_type([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const browserTypeRegex = new RegExp(browserTypeTag, 'gi');");
  code.push("    while ((match = browserTypeRegex.exec(text)) !== null) {");
  code.push("      const s = this.attr(match[1], 'selector');");
  code.push("      const t = this.attr(match[1], 'text');");
  code.push("      if (s && t) candidates.push({ index: match.index, tool: { name: 'browser_type', selector: s, text: t } });");
  code.push("    }");
  code.push("");
  code.push("    // browser_evaluate_script");
  code.push("    const browserEvalTag = '\\\\u003Cbrowser_evaluate_script([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const browserEvalRegex = new RegExp(browserEvalTag, 'gi');");
  code.push("    while ((match = browserEvalRegex.exec(text)) !== null) {");
  code.push("      const scriptAttr = this.attr(match[1], 'script');");
  code.push("      if (scriptAttr) candidates.push({ index: match.index, tool: { name: 'browser_evaluate_script', script: scriptAttr } });");
  code.push("    }");
  code.push("");
  code.push("    // browser_screenshot");
  code.push("    const browserScreenshotTag = '\\\\u003Cbrowser_screenshot[\\\\s\\\\S]*?\\\\/?\\\\u003E';");
  code.push("    const browserScreenshotRegex = new RegExp(browserScreenshotTag, 'gi');");
  code.push("    while ((match = browserScreenshotRegex.exec(text)) !== null) {");
  code.push("      candidates.push({ index: match.index, tool: { name: 'browser_screenshot' } });");
  code.push("    }");
  code.push("");
  code.push("    // run_command");
  code.push("    const runCommandTag = '\\\\u003Crun_command([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const runCommandRegex = new RegExp(runCommandTag, 'gi');");
  code.push("    while ((match = runCommandRegex.exec(text)) !== null) {");
  code.push("      const c = this.attr(match[1], 'command');");
  code.push("      if (c) candidates.push({ index: match.index, tool: { name: 'run_command', command: c } });");
  code.push("    }");
  code.push("");
  code.push("    // send_terminal_input (block style)");
  code.push("    const sendTerminalBlockTag = '\\\\u003Csend_terminal_input([\\\\s\\\\S]*?)\\\\u003E([\\\\s\\\\S]*?)\\\\u003C\\\\u002Fsend_terminal_input\\\\s*\\\\u003E';");
  code.push("    const sendTerminalInputBlockRegex = new RegExp(sendTerminalBlockTag, 'gi');");
  code.push("    while ((match = sendTerminalInputBlockRegex.exec(text)) !== null) {");
  code.push("      const termName = this.attr(match[1], 'terminal_name');");
  code.push("      if (termName) {");
  code.push("        candidates.push({");
  code.push("          index: match.index,");
  code.push("          tool: { name: 'send_terminal_input', terminal_name: termName.trim(), content: match[2] } as any,");
  code.push("        });");
  code.push("      }");
  code.push("    }");
  code.push("");
  code.push("    // send_terminal_input (self-closing style)");
  code.push("    const sendTerminalSelfTag = '\\\\u003Csend_terminal_input([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const sendTerminalInputSelfRegex = new RegExp(sendTerminalSelfTag, 'gi');");
  code.push("    while ((match = sendTerminalInputSelfRegex.exec(text)) !== null) {");
  code.push("      if (match[0].includes('\\u003C\\\\u002Fsend_terminal_input')) continue;");
  code.push("      const termName = this.attr(match[1], 'terminal_name');");
  code.push("      const input = this.attr(match[1], 'input');");
  code.push("      if (termName && input) {");
  code.push("        candidates.push({");
  code.push("          index: match.index,");
  code.push("          tool: { name: 'send_terminal_input', terminal_name: termName.trim(), content: input } as any,");
  code.push("        });");
  code.push("      }");
  code.push("    }");
  code.push("");
  code.push("    // close_terminal");
  code.push("    const closeTerminalTag = '\\\\u003Cclose_terminal([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const closeTerminalRegex = new RegExp(closeTerminalTag, 'gi');");
  code.push("    while ((match = closeTerminalRegex.exec(text)) !== null) {");
  code.push("      const termName = this.attr(match[1], 'terminal_name');");
  code.push("      if (termName) {");
  code.push("        candidates.push({");
  code.push("          index: match.index,");
  code.push("          tool: { name: 'close_terminal', terminal_name: termName.trim() } as any,");
  code.push("        });");
  code.push("      }");
  code.push("    }");
  code.push("");
  code.push("    // read_terminal");
  code.push("    const readTerminalTag = '\\\\u003Cread_terminal([\\\\s\\\\S]*?)\\\\/?\\\\u003E';");
  code.push("    const readTerminalRegex = new RegExp(readTerminalTag, 'gi');");
  code.push("    while ((match = readTerminalRegex.exec(text)) !== null) {");
  code.push("      const termName = this.attr(match[1], 'terminal_name');");
  code.push("      if (termName) {");
  code.push("        const chars = this.attr(match[1], 'chars');");
  code.push("        candidates.push({");
  code.push("          index: match.index,");
  code.push("          tool: { name: 'read_terminal', terminal_name: termName.trim(), chars: chars || undefined } as any,");
  code.push("        });");
  code.push("      }");
  code.push("    }");
  code.push("");
  code.push("    // list_terminals");
  code.push("    const listTerminalsTag = '\\\\u003Clist_terminals[\\\\s\\\\S]*?\\\\/?\\\\u003E';");
  code.push("    const listTerminalsRegex = new RegExp(listTerminalsTag, 'gi');");
  code.push("    while ((match = listTerminalsRegex.exec(text)) !== null) {");
  code.push("      candidates.push({ index: match.index, tool: { name: 'list_terminals' } });");
  code.push("    }");
  code.push("");
  code.push("    if (candidates.length === 0) return [];");
  code.push("    candidates.sort((a, b) => a.index - b.index);");
  code.push("    return [candidates[0].tool];");
  code.push("  }");
  code.push("");
  code.push("  public formatToolStatus(");
  code.push("    toolName: string,");
  code.push("    status: 'running' | 'success' | 'error',");
  code.push("    target: string,");
  code.push("    result?: string,");
  code.push("    checkpointId?: string,");
  code.push("    code?: string,");
  code.push("    terminalName?: string,");
  code.push("  ): any {");
  code.push("    return {");
  code.push("      type: 'toolStatus',");
  code.push("      toolName,");
  code.push("      status,");
  code.push("      target,");
  code.push("      result,");
  code.push("      checkpointId,");
  code.push("      code,");
  code.push("      terminalName,");
  code.push("    };");
  code.push("  }");
  code.push("}");
  code.push("");
  
  return code.join('\n');
}

const result = buildParser();
fs.writeFileSync('src/agent/agent-parser.ts', result, 'utf8');
console.log('Done - wrote ' + result.length + ' bytes');
